spring:
    mail:
        host: smtp.gmail.com
        port: 587
        username: womeninretail2@gmail.com
        password: rvegwmkyixpyvhqg
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true